services:
  redis:
    image: redis:7-alpine
    container_name: medilabo-redis
    ports:
      - "6379:6379"             # Redis dispo sur localhost:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data        # persistance des sessions

volumes:
  redis_data:

services:
  mongo:
    image: mongo:7
    container_name: medilabo-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: medilabo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
