services:
  redis:
    image: redis:7-alpine
    container_name: medilabo-redis
    profiles: ["infra"]
    ports:
      - "6379:6379"             # Redis dispo sur localhost:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data        # persistance des sessions

  mongo:
    image: mongo:7
    container_name: medilabo-mongo
    profiles: ["infra"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: medilabo
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8
    container_name: medilabo-mysql
    profiles: ["infra"]
    environment:
      MYSQL_DATABASE: medilabo_patients
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-medilabo}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-medilabo}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${MYSQL_ROOT_PASSWORD:-root}"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes: 
      - mysql_data:/var/lib/mysql

volumes:
  redis_data:
  mongo_data:
  mysql_data:
 
