server:
  port: 8081

spring:
  cloud:
    gateway:
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:5173"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            allowCredentials: true
      routes:
        - id: patient-service
          uri: http://localhost:8080
          predicates: [ Path=/api/** ]

        - id: notes-service
          uri: http://localhost:8082
          predicates: [ Path=/api/notes/** ]

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateways"
