server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info  # (le listing des routes gateway n'est pas dispo en MVC ancien)

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: notes-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/notes/**

          - id: notes-debug
            uri: http://localhost:8082
            predicates:
                - Path=/api/debug/**

          - id: patient-login
            uri: http://localhost:8080
            predicates:
              - Path=/api/connexion
          - id: patient-logout
            uri: http://localhost:8080
            predicates:
              - Path=/api/logout
          - id: patient-me
            uri: http://localhost:8080
            predicates:
              - Path=/api/me
          - id: patient-crud
            uri: http://localhost:8080
            predicates:
              - Path=/api/patients/**
logging:
  level:
    org.springframework.session: DEBUG