server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/medilabo
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
    redis:
      namespace: medilabo:sessions   # même namespace que tes autres MS


logging:
  level:
    org.springframework.security: INFO
